### ISSUE TITLE
Yo compatibility problem?

### ISSUE THREAD

**Issue by lrkwz** [moifort/generator-jhipster-google-analytics#2]
Hello I wish to use this plugin with a jhipster 3.5.1 generated application but ... (see complete info at the end)
```
$ yo
? 'Allo Luca! What would you like to do? Jhipster Google Analytics

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster-google-analytics


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the JHipster |
   `---------´   |     Google Analytics     |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? (1/2) What is your Google analytics tracking ID? UA-56299928-1
? (2/2) What is the domain name of your application? garanteasy.com
Composing JHipster configuration with module google-analytics
Reading the JHipster project configuration for your module

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addAngularJsConfig is not a function
    at module.exports.yeoman.generators.Base.extend.writing (/usr/lib/node_modules/generator-jhipster-google-analytics/generators/app/index.js:82:22)
    at /usr/lib/node_modules/generator-jhipster-google-analytics/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

##### **JHipster Version(s)**

```
garanteasy@0.0.0 /home/lrkwz/garanteasy2/garanteasy
└── generator-jhipster@3.5.1 


```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "garanteasy",
    "packageName": "com.garanteasy",
    "packageFolder": "com/garanteasy",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "20c6a6250171f9df615086d6fe2411e36c498ad5",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it",
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 1.9.1

node: v4.2.1

npm: 2.15.11

bower: 1.7.9

gulp:
[16:34:08] CLI version 1.2.2
[16:34:08] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.3, build 6b644ec

docker-compose version 1.8.1, build 878cff1
